  on:
    push:
      branches:
        - master








  jobs:
    build:
      runs-on: ubuntu-latest


      steps:
        - name: "Printing current directory"
          run: pwd
        - name: "printing folder content"
          run: ls
